# Generated by Django 6.0.5 on 2026-05-31 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogoSepomex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_postal', models.CharField(max_length=5)),
                ('clave_entidad_federativa', models.IntegerField()),
                ('descripcion_entidad_federativa', models.CharField(max_length=100)),
                ('clave_delegacion_municipio', models.IntegerField()),
                ('descripcion_delegacion_municipio', models.CharField(max_length=150)),
                ('clave_localidad', models.IntegerField(blank=True, null=True)),
                ('descripcion_localidad', models.CharField(blank=True, max_length=150, null=True)),
                ('clave_colonia', models.IntegerField()),
                ('descripcion_colonia', models.CharField(max_length=150)),
            ],
            options={
                'verbose_name': 'Registro Sepomex',
                'verbose_name_plural': 'Catálogo Sepomex',
                'db_table': 'catalogo_sepomex',
                'indexes': [models.Index(fields=['codigo_postal'], name='idx_codigo_postal')],
            },
        ),
    ]
