# Generated by Django 6.0.6 on 2026-06-13 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socios', '0002_socio'),
    ]

    operations = [
        migrations.AddField(
            model_name='socio',
            name='codigo_postal',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='Código Postal'),
        ),
        migrations.AddField(
            model_name='socio',
            name='colonia',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Colonia'),
        ),
        migrations.AddField(
            model_name='socio',
            name='municipio',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Delegación o Municipio'),
        ),
    ]
