# Generated by Django 6.0.5 on 2026-05-31 08:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('clave_producto', models.BigIntegerField(help_text='Clave compuesta oficial por tipo de operación, producto y subproducto', primary_key=True, serialize=False)),
                ('tipo_operacion', models.CharField(max_length=255)),
                ('producto', models.CharField(max_length=255)),
                ('subproducto', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'db_table': 'productos',
            },
        ),
        migrations.CreateModel(
            name='Causa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave_causa', models.IntegerField()),
                ('descripcion_causa', models.TextField()),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='causas', to='consultas.producto')),
            ],
            options={
                'verbose_name': 'Causa',
                'verbose_name_plural': 'Causas',
                'db_table': 'causas',
            },
        ),
    ]
