# Generated by Django 6.0.6 on 2026-06-13 18:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultas', '0001_initial'),
        ('socios', '0002_socio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Queja',
            fields=[
                ('folio', models.CharField(blank=True, max_length=50, primary_key=True, serialize=False, verbose_name='Folio')),
                ('fecha_consulta', models.DateField(verbose_name='Fecha de Consulta')),
                ('estado', models.IntegerField(choices=[(1, 'Abierto/En proceso'), (2, 'Concluido/Cerrado')], default=1, verbose_name='Estado')),
                ('fecha_cierre', models.DateField(blank=True, null=True, verbose_name='Fecha de Cierre')),
                ('medio', models.CharField(default='Teléfono', max_length=100, verbose_name='Medio de Recepción')),
                ('causa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quejas', to='consultas.causa', verbose_name='Causa')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quejas', to='consultas.producto', verbose_name='Producto')),
                ('socio_referencia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quejas', to='socios.socio', verbose_name='Socio de Referencia')),
            ],
            options={
                'verbose_name': 'Queja',
                'verbose_name_plural': 'Quejas',
                'db_table': 'quejas',
            },
        ),
    ]
